[package]
name = "rover_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
embedded-hal-02 = { workspace = true }
embedded-hal-1 = { workspace = true }
libm = { workspace = true }

[dependencies.uom]
version = "0.36.0"
default-features = false
features = ["f32", "autoconvert", "si", "serde"]
